all:
  - IndexPrice # core
  - BrokerInfo # onetime
  - StockInfo
  - ContractInfo
  - StockPrice # daily
  - BrokerTransaction
  - FutureLargeTrader
  - StockCapReduction # periodic
  - StockDividend
  - StockSplit
  - StockRevenue
  - AdjustedPrice # transformation

raw: # no transform, only scrape
  - IndexPrice # core
  - BrokerInfo # onetime
  - StockInfo
  - ContractInfo
  - StockPrice # daily
  - BrokerTransaction
  - FutureLargeTrader
  - StockCapReduction # periodic
  - StockDividend
  - StockSplit
  - StockRevenue

standard:
  - IndexPrice
  - StockPrice
  - Stock
  - StockCapReduction
  - StockDividend
  - StockSplit
  - AdjustedPrice

# === by scraper-type ===
core:
  - IndexPrice

onetime:
  - BrokerInfo
  - StockInfo
  - ContractInfo

daily:
  - StockPrice
  - BrokerTransaction
  - FutureLargeTrader

periodic:
  - StockCapReduction
  - StockDividend
  - StockSplit
  - StockRevenue

transformation:
  - AdjustedPrice