core: # date_chunk
  - IndexPrice

onetime:
  - BrokerInfo
  - StockInfo
  - ContractInfo

daily:
  - StockPrice
  - BrokerTransaction
  - FutureLargeTrader

periodic:  
  - StockCapReduction
  - StockDividend
  - StockSplit
  - StockRevenue

date_chunk: null

stock_chunk: null

transformation:
  - AdjustedPrice